### PR TITLE
Package via poetry

### PR DESCRIPTION
**Pull request by thrix**
And update README.md

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by thrix** [comment]
Seems will need a bit more love:

```
$ poetry install
/home/mvadkert/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
The currently activated Python version 2.7.17 is not supported by the project (^3.6).
Trying to find and use a compatible version. 
Using python3 (3.7.6)
Creating virtualenv fingertip-4UZfIHy7-py3.7 in /home/mvadkert/.cache/pypoetry/virtualenvs
Installing dependencies from lock file


Package operations: 26 installs, 0 updates, 0 removals

  - Installing pycparser (2.20)
  - Installing certifi (2019.11.28)
  - Installing cffi (1.14.0)
  - Installing chardet (3.0.4)
  - Installing idna (2.9)
  - Installing six (1.14.0)
  - Installing smmap (3.0.1)
  - Installing urllib3 (1.25.8)
  - Installing bcrypt (3.1.7)
  - Installing cryptography (2.8)
  - Installing gitdb (4.0.2)
  - Installing monotonic (1.5)
  - Installing msgpack (1.0.0)
  - Installing ptyprocess (0.6.0)
  - Installing pynacl (1.3.0)
  - Installing requests (2.23.0)
  - Installing cachecontrol (0.12.6)
  - Installing cloudpickle (1.3.0)
  - Installing colorlog (4.1.0)
  - Installing fasteners (0.15)
  - Installing gitpython (3.1.0)
  - Installing lockfile (0.12.2)
  - Installing paramiko (2.7.1)
  - Installing pexpect (4.8.0)
  - Installing pyxdg (0.26)
  - Installing requests-mock (1.7.0)
  - Installing fingertip (0.1.0)
[mvadkert@freedom ~/git/github.com/fingertip] (package-via-poetry)$ python -m fingertip
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib64/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "fingertip/__init__.py", line 4, in <module>
    from fingertip.machine import build, transient
  File "fingertip/machine.py", line 8
    import fingertip.exec
                        ^
SyntaxError: invalid syntax
```

**Comment by thrix** [comment]
Oh python 2.7 :D :D nm :) my bad

**Comment by thrix** [comment]
This now works for me. Published as documented on Pypi, set you as owner @t184256 

https://pypi.org/project/fingertip/

**Comment by t184256** [comment]
Oh wow, thanks for going through this hassle instead of me! I'll also add readme and repository, bump the version and try to push another version to PyPi to make sure I can do it too.

**Comment by t184256** [comment]
Worked fine, thanks again. Even rendered Markdown on pypi, something that I never got working previously.

**Comment by thrix** [comment]
@t184256 nice, more smooth then I would expect :)

**Pull request merged**
